name: Deploy

on:
  workflow_run:
    workflows: ["Build and Test"]

    types:
      - completed

    branches:
      - main

jobs:
  check-workflow-success:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      success: ${{ steps.check.outputs.success }}
    steps:
      - id: check
        run: echo "success=true" >> $GITHUB_OUTPUT

  download-package:
    needs: check-workflow-success
    if: needs.check-workflow-success.outputs.success == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Package Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-test.yml
          name: package
          path: .

  deploy-us-east-1:
    needs: download-package
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      aws-region: us-east-1
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      bucket-name: ${{ secrets.AWS_US_EAST_1_BUCKET }}

  deploy-us-east-2:
    needs: download-package
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      aws-region: us-east-2
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      bucket-name: ${{ secrets.AWS_US_EAST_2_BUCKET }}
