name: Deploy

on:
  workflow_run:
    workflows: ["Build and Test"]

    types:
      - completed

    branches:
      - main

jobs:
  download-package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          workflow: build-test.yml
          name: package
          path: .

  deploy-us-east-1:
    needs: download-package
    with:
      aws-region: us-east-1
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      bucket-name: ${{ secrets.AWS_US_EAST_1_BUCKET }}

  deploy-us-east-2:
    needs: download-package
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      aws-region: us-east-2
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      bucket-name: ${{ secrets.AWS_US_EAST_2_BUCKET }}
